name: Interactive tmate session

# manuel başlatma için workflow_dispatch kullanıyoruz
on:
  workflow_dispatch:

jobs:
  tmate-shell:
    runs-on: ubuntu-latest
    # uzun canlı oturumlar için timeout artırabilirsin
    timeout-minutes: 180

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install common tools (optional)
      run: |
        sudo apt update
        sudo apt install -y git build-essential curl wget ca-certificates
      # eğer network erişimi gerekmezse bu step'i çıkarabilirsin

    - name: Start tmate session (open interactive SSH/web shell)
      uses: mxschmitt/action-tmate@v3
      # no input required; action otomatik oluşturur ve connection bilgilerini log'a basar

    # optional: after tmate started, bu step ile birşeyler çalıştırabilirsin
    # fakat genelde tmate step sonrası runner interaktif olurken bu step bloklanabilir.
    # - name: Do something (optional)
    #   run: echo "you can pre-run setup here if needed"

