name: Interactive tmate session

# manuel başlatma için workflow_dispatch kullanıyoruz
on:
  workflow_dispatch:

jobs:
  tmate-shell:
    runs-on: ubuntu-latest
    # uzun canlı oturumlar için timeout artırabilirsin
    timeout-minutes: 720

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install common tools (optional)
      run: |
        sudo apt update
        sudo apt install -y git curl wget ca-certificates
        mkdir ${{ github.workspace }}/output
      # eğer network erişimi gerekmezse bu step'i çıkarabilirsin
    - name: Pull Debian image and prepare environment
      run: |
        docker pull debian:bookworm
        docker run -d --name dev \
          -v ${{ github.workspace }}/output:/mnt/output \
          debian:bookworm sleep infinity
          docker exec dev apt-get update
          docker exec dev apt-get install -y sudo nano make gcc git curl build-essentinal crossbuild-essential-arm64 qemu-user-static binfmt-support fdisk gzip rsync libssl-dev libncurses5-dev make wget tar python3 busybox
    - name: Start tmate session (open interactive SSH/web shell)
      uses: mxschmitt/action-tmate@v3
      # no input required; action otomatik oluşturur ve connection bilgilerini log'a basar

    # optional: after tmate started, bu step ile birşeyler çalıştırabilirsin
    # fakat genelde tmate step sonrası runner interaktif olurken bu step bloklanabilir.
    # - name: Do something (optional)
    #   run: echo "you can pre-run setup here if needed"

    - name: Upload build artifacts
      if: always()   # tmate oturumu iptal edilse bile çalışır
      uses: actions/upload-artifact@v4
      with:
        name: output-files
        path: /home/runner/work/trdroid/output
